# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup

description:      '『he looks like a dog so』 『because he is a PM』'
url:              http://cellier.me

author:
  name:           'cellier'
  email:          cellier@mail.com

paginate:         5

# Custom vars
version:          0.0.3

# Comments

comments :
    provider : duoshuo
    duoshuo :
          short_name : cellier-me


